FROM apache/spark:3.5.1

USER root

# Нормальный HOME
ENV HOME=/opt/spark
ENV SPARK_LOCAL_DIRS=/opt/spark/tmp

RUN mkdir -p /opt/spark/tmp /opt/spark/.ivy2 && \
    chmod -R 777 /opt/spark

RUN curl -fL -o /opt/spark/jars/spark-sql-kafka-0-10.jar \
    https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.1/spark-sql-kafka-0-10_2.12-3.5.1.jar

RUN curl -fL -o /opt/spark/jars/spark-token-provider-kafka-0-10.jar \
    https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.1/spark-token-provider-kafka-0-10_2.12-3.5.1.jar

RUN curl -fL -o /opt/spark/jars/commons-pool2.jar \
    https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar

RUN curl -fL -o /opt/spark/jars/kafka-clients.jar \
    https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.1/kafka-clients-3.5.1.jar

WORKDIR /app
