security.protocol=SASL_SSL
sasl.mechanism=PLAIN

sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
 username="admin" \
 password="admin-password";

ssl.truststore.location=/etc/kafka/ssl/keystores/kafka.truststore.jks
ssl.truststore.password=123456
ssl.truststore.type=JKS
ssl.endpoint.identification.algorithm=HTTPS
